[profile.default]
  libs = ['node_modules', 'lib']
  out = "out"
  src = "src"

  evm_version = 'london'
  optimizer = true
  optimizer_runs = 2499
  solc_version = '0.8.28'

  remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "risc0/=lib/risc0-ethereum/contracts/src/",
  ]

  # forge-deploy
  fs_permissions = [
    { access = "read-write", path = "./deployments" },
    { access = "read", path = "./out" },
    { access = "read", path = "./deployment-config.json" }
  ]

[rpc_endpoints]
linea_sepolia = "${LINEA_SEPOLIA_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
arbitrum_sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
testnet1 = "${TESTNET1_RPC_URL}"
testnet2 = "${TESTNET2_RPC_URL}"
anvil1 = "http://localhost:8545"
anvil2 = "http://localhost:8546"
