[profile.default]
src = "src"
out = "out"
libs = ['node_modules', 'lib']

solc_version='0.8.27'
evm_version='paris'
optimizer = true
optimizer_runs = 9000


# forge-dpeloy
fs_permissions = [
	{ access = "read-write", path = "./deployments"},
	{ access = "read", path = "./out"}
]