[profile.default]
  libs = ['node_modules', 'lib']
  out = "out"
  src = "src"

  evm_version = 'london'
  optimizer = true
  optimizer_runs = 2499
  solc_version = '0.8.28'

  remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "risc0/=lib/risc0-ethereum/contracts/src/",
    "forge-std/=lib/forge-std/src/",
    "mendi/=lib/lending-protocol/contracts/",
  ]

  # forge-deploy
  fs_permissions = [
    { access = "read-write", path = "./deployments" },
    { access = "read", path = "./out" },
    { access = "read", path = "./deployment-config.json" },
  ]

[rpc_endpoints]
linea_sepolia = "${LINEA_SEPOLIA_RPC_URL}"
op_sepolia = "${OP_SEPOLIA_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
arbitrum_sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
anvil1 = "http://localhost:8545"
anvil2 = "http://localhost:8546"

[etherscan]
linea_sepolia = {chain = "59141", url = "https://api-sepolia.lineascan.build/api", key = "${LINEA_SEPOLIA_ETHERSCAN_API_KEY}"}
op_sepolia = {chain = "11155420", url = "https://api-sepolia-optimistic.etherscan.io/api", key = "${OP_SEPOLIA_ETHERSCAN_API_KEY}"}
sepolia = {chain = "11155111", url = "https://api-sepolia.etherscan.io/api", key = "${SEPOLIA_ETHERSCAN_API_KEY}"}
arbitrum_sepolia = {url = "https://api-sepolia-arbitrum.etherscan.io/api", key = "${ARBITRUM_SEPOLIA_ETHERSCAN_API_KEY}"}
base_sepolia = {url = "https://api-sepolia-base.etherscan.io/api", key = "${BASE_SEPOLIA_ETHERSCAN_API_KEY}"}
