name: Run Foundry Forge Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Solidity tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 'latest' 

      - name: Install Dependencies
        run: yarn install

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Foundry dependencies
        run: forge install

      - name: Check contract sizes
        run: forge build --sizes --skip "script"
        id: build

      - name: Run Solidity tests
        run: forge test 
        id: test
