name: Run Foundry Forge Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Foundry
      run: |
        curl -L https://foundry.paradigm.xyz | bash
        bash -c "$(curl -fsSL https://raw.githubusercontent.com/foundry-rs/foundry/master/foundryup/install.sh)"
        export PATH="$HOME/.foundry/bin:$PATH"
        foundryup

    - name: Cache foundry dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.foundry/cache
          lib
        key: ${{ runner.os }}-foundry-${{ hashFiles('foundry.toml') }}

    - name: Install Dependencies
      run: |
        export PATH="$HOME/.foundry/bin:$PATH"
        forge install

    - name: Run Forge Tests
      run: |
        export PATH="$HOME/.foundry/bin:$PATH"
        forge test --gas-report
